name:        guake-cl
version:     v0.5.0
summary:     change guake's colour scheme
description: change guake's colour scheme
base: core20
confinement: strict
grade: stable

apps:
  guake-cl:
    command: bin/guake-cl
    plugs:
    - gsettings

parts:
  guake-cl:
    plugin: go
    source: .
    source-type: local
    build-packages:
      - gcc
    stage-packages:
      - dconf-cli
